# Generated by Django 2.2.2 on 2019-07-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='impresiones3d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramaje', models.CharField(max_length=10)),
                ('tiempo', models.CharField(max_length=10)),
                ('cantidad', models.CharField(max_length=10)),
                ('filamento', models.CharField(max_length=40)),
                ('picture', models.ImageField(upload_to='media/uploads/pictures')),
            ],
        ),
    ]
