# Generated by Django 2.2.2 on 2019-07-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresiones3d',
            name='picture',
            field=models.ImageField(upload_to='media/uploads'),
        ),
    ]
