# Generated by Django 2.2.2 on 2019-07-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190702_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresiones3d',
            name='nombre',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
